apiVersion: v1
kind: Namespace
metadata:
  name: sample-app
status:
  phase: Active
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: sample-app
data:
  default.conf: |
    server {
      listen 80;
      listen [::]:80;
      server_name  _;
      location / {
        add_header Content-Type text/plain; # Prevents download
        return 200 "Hello world! Kubernetes + Let's encrypt demo.";
      }
    }
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: nginx
  name: nginx
  namespace: sample-app
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-configs
              mountPath: /etc/nginx/conf.d
      # Load the configuration files for nginx
      volumes:
        - name: nginx-configs
          configMap:
            name: nginx-config
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: sample-app
spec:
  selector:
    app: nginx
  ports:
    - protocol: "TCP"
      port: 80
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "sample-app-ingress"
  namespace: "sample-app"
  annotations:
    certmanager.k8s.io/acme-challenge-type: http01
spec:
  tls:
    - hosts:
        - sample-app.scotthaines.dev
      secretName: sample-app-crt
  rules:
    - host: sample-app.scotthaines.dev
      http:
        paths:
          - path: /
            backend:
              serviceName: nginx
              servicePort: 80
