variable "project-name" {}
variable "k8s-bastion-fqdn" {}
variable "rancher-proxy-fqdn" {}
variable "dns-k8s-bastion-username" {}
variable "dns-k8s-bastion-password" {}
variable "dns-rancher-proxy-username" {}
variable "dns-rancher-proxy-password" {}
variable "ssh-username" {}
variable "ssh-private-key" {}
variable "rancher-admin-password" {}
